config/routes.rb
Rails.application.routes.draw do
 devise_for :users, :skip => [:sessions], :controllers => { :registrations => "user_registrations" }
  as :user do
    get 'signin' => 'devise/sessions#new', :as => :new_user_session
    post 'signin' => 'devise/sessions#create', :as => :user_session
    delete 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  root 'static_pages#landing_page'
  get 'about' =>'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'static_pages/index'

  post 'static_pages/thank_you'

  get 'products/index'

  get 'users' => 'users#index'
  get 'users/show'

  get 'tasks/show'

  get 'tasks/new'

  get 'tasks/edit'

  post 'payments/create'

  resources :products do
    resources :comments
  end

 resources :users

 resources :orders, only: [:index, :show, :create, :destroy]

end

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(@user.errors.count, "error") %>.
      </div>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div class="container-fluid">
    <div class="row">

      <div class="col-md-3 col-lg-4 col-xs-6">
        <p class="copy"> &copy; Judith Deurvorst <%= Time.now.strftime('%Y') %> </p>
      </div><! -- col -->

      <div class="col-md-9 col-lg-8 col-xs-6">
        <div class="row">

          <ul>
            <% if user_signed_in? %>
            <div class="col-md-8">
              <p class="text hidden-xs hidden-sm">Logged in as <%= current_user.email %> </p>
            </div> <!-- col-md-8 -->

            <div class="col-md-4 pull-right user">
              <li class="<%= 'active' if current_page?(new_user_session_path) %> no-list" >
                <%= link_to("Edit profile", edit_user_registration_path) %> |
                <%= link_to("Logout", destroy_user_session_path, :method => :delete) %>
              </li>
            </div><!-- col-md-4 -->

            <% else %>
            <div class="col-md-4 pull-right user">
              <li>
                <%= link_to("Sign up", new_user_registration_path) %> |
               <%= link_to("Login", new_user_session_path) %>
              </li>
             <% end %>
            </div> <!-- col-md-4 -->

          </ul>

        </div><!-- subrow -->
      </div> <!-- col-md-9 -->
    </div><!-- row -->
   </div> <!-- container-->
</footer>

app/views/shared/_head.html.erb
<head>
  <title>Your Favorite Bookstore</title>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700,600,300|Roboto+Slab:400,300,700' rel='stylesheet' type='text/css'>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"> </script>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>

</head>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
              data-target="#bs-example-navbar-collapse-1" aria-expanded="false"
              aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Your favorite bookstore", root_path, class: "navbar-brand" %>
    </div> <!-- navbar-header -->

    <div  class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="<%= 'active' if current_page?(products_path) %>">
          <%= link_to "Books", products_path %> </li>
        <li class="<%= 'active' if current_page?(orders_path) %>">
          <%= link_to "Orders", orders_path %> </li>
        <li class="<%= 'active' if current_page?(about_path) %>">
          <%= link_to "About", about_path %></li>
        <li class="<%= 'active' if current_page?(contact_path) %>">
          <%= link_to "Contact", contact_path %></li>
        <li style="padding-top: 22px;">
          <%= form_tag("/products", method: "get", html: { class: "navbar-form navbar-right" }) do %>
              <%= text_field_tag(:q) %>
              <%= submit_tag("Search", html: { class: "btn btn-default search" })%>
        </li>
        <% end %>
      </ul>

    </div> <!-- #navbar -->
  </div> <!-- container -->
</nav> <!-- navbar -->

app/views/shared/_product.html.erb
<% cache product do %>
<div class="item col-xs-12 col-sm-6 col-lg-4">
  <div class="thumbnail">
    <p class="img group list-group-image"><%= image_tag product.image_url, width: "110" %></p>
    <div class="caption">
      <h3 class="group inner list-group-item-heading strong"> <%= product.name %></h3>
      <h5><%= product.author %></h5>
      <p class="group inner list-group-item-text"><%= product.description %></p>
      <div class="row">
        <div class="col-xs-12 col-md-6">
          <p class="lead"><%= number_to_currency(product.price, unit: "€ ") %> </p>
        </div> <!-- col -->
        <div class="col-xs-12 col-md-6">
          <%= link_to 'Show', product, class: "btn btn-default" %>
          <%= link_to 'Edit', edit_product_path(product), class: "btn btn-default" %>
          <%= link_to 'Destroy', product, class: "btn btn-warning", method: :delete, data: { confirm: 'Are you sure?' } %>
        </div> <!-- col -->
      </div> <!-- row -->
        <% logger.debug "Book name: #{product.name}" %>
    </div> <!-- caption -->
  </div> <!-- thumbnail -->
</div> <!-- item -->
<% end %>

app/views/shared/_stripe_checkout_button.html.erb
<script
  src="https://checkout.stripe.com/checkout.js" class="stripe-button"
  data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
  data-amount="<%= (@product.price*100).to_i %>"
  data-name="<%= @product.name %>"
  data-description="<%= @product.description %>"
  data-image="<%= @product.image_url %>">
</script>